MVC/Controllers/AuthenticationController.cs
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MVC.Controllers
{
    public class AuthenticationController : Controller
    {
        EmployeeMgmtEntities1 db = new EmployeeMgmtEntities1();
        // GET: Authentication
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(true)]
        public ActionResult Login(User user)
        {
            var query = from u in db.Users
                        where u.username == user.username && u.password == user.password
                        select u;
            User matchedUser = query.FirstOrDefault();
            if (matchedUser != null)
            {
                //In order to setup login, add <authentication mode="Forms"> to web.config
                FormsAuthentication.SetAuthCookie(matchedUser.username, true);
                return RedirectToAction("Index","Employee");
            } else
            {
                ViewData["failed"] = "Authentication failed";
                return View();
            }

        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Employee");
        }
    }
}

MVC/Views/Authentication/Login.cshtml
@model MVC.Models.User

@if(ViewData["failed"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        @ViewData["failed"]
    </div>
}

@using (Html.BeginForm("Login", "Authentication", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.DisplayName("Username")
        @Html.TextBoxFor(model => model.username, new { @class="form-control" })
        @Html.ValidationMessageFor(model=>model.username)
    </div>

    <div class="form-group">
        @Html.DisplayName("Password")
        @Html.TextBoxFor(model => model.password, new { type = "password", @class = "form-control" })
        @Html.ValidationMessageFor(model => model.password)
    </div>

    <button type="submit" class="btn btn-primary mt-3">Login</button>
}