MVC/Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string dept { get; set; }
    }
}

MVC/Controllers/EmployeeController.cs
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    //Add authorize annotation to prevent unauthenticated access
    //Type is controller level filter ==> filter for All controller methods
    [Authorize]
    public class EmployeeController : Controller
    {
        EmployeeMgmtEntities db = new EmployeeMgmtEntities();
        // GET: Employee

        //Add authorize annotation to prevent unauthenticated access
        //Type is action filter ==> filter for Only Index() method
        //[Authorize]
        public ActionResult Index()
        {
            IEnumerable<Employee> employees = db.Employees;
            return View(employees);
        }

        /**
         * View Detail of employee
         */
        public ActionResult Show(int id)
        {
            Employee employee = db.Employees.Find(id);
            return View(employee);
        }

        public ActionResult Create()
        {
            Employee employee = new Employee();
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employee employee)
        {
            db.Employees.Add(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            Employee employee = db.Employees.Find(id);
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Employee employee)
        {
            db.Entry(employee).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC/Views/Employee/Create.cshtml
@model MVC.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Employee", FormMethod.Post, new { @class="form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.Label("Name")
        @Html.TextBoxFor(model => model.name, new { @class="form-control" })
    </div>

    <div>
        @Html.Label("Dept")
        @Html.TextBoxFor(model => model.dept, new { @class = "form-control" })
    </div>

    <p><button type="submit" class="btn btn-primary">Create</button></p>
}

MVC/Views/Employee/Edit.cshtml
@model MVC.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Update</h2>

@using (Html.BeginForm("Edit", "Employee", FormMethod.Post, new { @class="form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.Label("Name")
        @Html.TextBoxFor(model => model.name, new { @class="form-control" })
    </div>

    <div>
        @Html.Label("Dept")
        @Html.TextBoxFor(model => model.dept, new { @class = "form-control" })
    </div>

    <p><button type="submit" class="btn btn-primary">Update</button></p>
}

MVC/Views/Employee/Index.cshtml
@model IEnumerable<MVC.Models.Employee>
@using MVC.Models

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div style="margin-bottom:20px">@Html.ActionLink("Create", "Create", "Employee", new { @class = "btn btn-primary" })</div>

<table class="table table-striped">
    <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Dept</td>
        <td></td>
    </tr>

    @foreach (Employee employee in Model)
    {
        <tr>
            <td>@employee.ID</td>
            <td>@employee.name</td>
            <td>@employee.dept</td>
            <td>
                @Html.ActionLink("Show", "Show", "Employee", new { id = employee.ID }, null)
                @Html.ActionLink("Edit", "Edit", "Employee", new { id = employee.ID }, null)
                @Html.ActionLink("Delete", "Delete", "Employee", new { id = employee.ID }, new { onclick = "return confirm('Are you sure')" })
            </td>
        </tr>
    }
</table>

MVC/Views/Employee/Show.cshtml
@model MVC.Models.Employee

@{
    ViewBag.Title = "Show";
}

<h2>Employee detail</h2>

<p>ID: @Model.ID</p>
<p>Name: @Model.name</p>
<p>Dept: @Model.dept</p>