MVC/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class Customer
    {
        public string Code { get; set; }

        public string Name { get; set; }

        public double Amount { get; set; }
    }
}

MVC/Controllers/CustomerController.cs
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Demo
        public ActionResult Index()
        {
            Customer c = new Customer();
            c.Name = "Camnh";
            c.Code = "CAMNH-123";
            c.Amount = 2090.34;
            return View("DisplayCustomer", c);
        }

        public ActionResult InputCustomer()
        {
            return View("InputCustomer");
        }

        public ActionResult ReceiveInputCustomer()
        {
            Customer c = new Customer();
            c.Name = Request.Form["Name"];
            c.Code = Request.Form["Code"];
            c.Amount = Convert.ToDouble(Request.Form["Amount"]);
            return View("DisplayCustomer", c);
        }

        public ActionResult PassViewData()
        {
            ViewData["myData"] = "123";
            return View("PassViewData");
        }

        /**
         * Display dynamic data to view by extending model.
         */
        public ActionResult DisplayDataDynamic()
        {
            CustomerDiscount customerDiscount = new CustomerDiscount();
            customerDiscount.Name = Request.Form["Name"];
            customerDiscount.Code = Request.Form["Code"];
            customerDiscount.Amount = Convert.ToDouble(Request.Form["Amount"]);
            customerDiscount.CalculateDiscount();
            
            return View(customerDiscount);
        }

        
    }
}

MVC/Views/Customer/DisplayCustomer.cshtml
@model MVC.Models.Customer

@{
    ViewBag.Title = "DisplayCustomer";
}

<h2>DisplayCustomer</h2>

<div>
    <p>Name: @Model.Name</p>
    <p>Code: @Model.Code</p>
    <p>Amount: @Model.Amount</p>
</div>

MVC/Views/Customer/DisplayDataDynamic.cshtml
@model MVC.Models.CustomerDiscount
   
@{
    ViewBag.Title = "DisplayDataDynamic";
}

<h2>DisplayDataDynamic</h2>

<div>
    <p>Name: @Model.Name</p>
    <p>Code: @Model.Code</p>
    <p>Amount: @Model.Amount</p>
    <p>Discount: @Model.Discount</p>
</div>

MVC/Views/Customer/InputCustomer.cshtml
@model MVC.Models.Customer

@{
    ViewBag.Title = "InputCustomer";
}

<h2>InputCustomer</h2>

@using (Html.BeginForm("DisplayDataDynamic", "Customer", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/Views/Customer/PassViewData.cshtml
@{
    ViewBag.Title = "PassViewData";
}

<h2>PassViewData</h2>

<p>View data: @ViewData["myData"] </p>